### ISSUE TITLE
Unable to simulate a automated reactor that cools other components down (without fuel rods)

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#39]
So... another simple design again
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000C10(h7ps,a0)|ean
What I'm trying to simulate is to replace the coolant cell when it completely cools down with another pre-heated one, but somehow it seems that this doesn't work. Nothing showed up in the "Component replaced" line.

**Comment by MauveCloud** [comment]
Fixed in v2.3.0.1

**Comment by KrisBigK** [comment]
It seems that this is still not properly fixed. Removing the left OC vent somehow makes it work again.
`0000000000000000000000000000000000000000000000000000000000000C000C00000000000C0D0C0D0C00000000000C000C000013(h2s0,a0)|ean`
![image](https://user-images.githubusercontent.com/34199560/54681774-2c089800-4b48-11e9-9ece-b81f79b184ea.png)
![image](https://user-images.githubusercontent.com/34199560/54682002-b5b86580-4b48-11e9-904f-3b477f7d3838.png)

**Comment by MauveCloud** [comment]
This is one where the new CSV output comes in handy.  That design is affected by quirks of the exchangers - you'll see in the first design that the reactor heat exchanger stays at 72 heat after about reactor tick 49, so it never hits the replacement threshold:
[reactor1.zip](https://github.com/MauveCloud/Ic2ExpReactorPlanner/files/2988737/reactor1.zip)
whereas with the left OC vent removed, it gets replaced for the first time at about reactor tick 96:
[reactor2.zip](https://github.com/MauveCloud/Ic2ExpReactorPlanner/files/2988747/reactor2.zip)
